project:
  type: default
  output-dir: expected
  render:
  - example/input.md

bibliography: example/references.bib
csl: example/chicago-author-date-with-note.csl

filters:
- quarto
- recursive-citeproc

profile:
  group: ['generate','test']