project:
  type: default

output-dir: test
  
render:
- test/input.md

bibliography: references.bib
csl: chicago-author-date-with-note.csl

filters:
- recursive-citeproc
- quarto

format:
  html:
    template: template.html

profile:
  group: ['generate','test']